/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Reciclagem;
import Reciclagem.Menu;
/**
 *
 * @author marco
 */
public class Menu extends javax.swing.JInternalFrame {
    private Menu menu;
    private Produtos produtos;
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        menu = new Menu();
        produtos = new Produtos();

        menu.setVisible(true);
        produtos.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btnProdutosDisp = new javax.swing.JButton();
        btnFazerMuamba = new javax.swing.JButton();
        btnMuambeirosDisp = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1200, 606));

        jPanel8.setBackground(new java.awt.Color(51, 51, 48));

        jLabel11.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel11.setText("SISTEMA DE GERENCIAMENTO DE COMÉRCIO PARALELO INTERNACIONAL");
        jLabel11.setToolTipText("");

        btnProdutosDisp.setBackground(new java.awt.Color(42, 42, 42));
        btnProdutosDisp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Produtos.png"))); // NOI18N
        btnProdutosDisp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProdutosDisp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutosDispActionPerformed(evt);
            }
        });

        btnFazerMuamba.setBackground(new java.awt.Color(42, 42, 42));
        btnFazerMuamba.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Muambar.png"))); // NOI18N
        btnFazerMuamba.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnMuambeirosDisp.setBackground(new java.awt.Color(42, 42, 42));
        btnMuambeirosDisp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cadastro de Muambeiros.png"))); // NOI18N
        btnMuambeirosDisp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMuambeirosDisp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMuambeirosDispActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(261, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(260, 260, 260))
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addGap(92, 92, 92)
                    .addComponent(btnMuambeirosDisp, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(73, 73, 73)
                    .addComponent(btnProdutosDisp, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(73, 73, 73)
                    .addComponent(btnFazerMuamba, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(92, Short.MAX_VALUE)))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(541, Short.MAX_VALUE))
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addGap(166, 166, 166)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnFazerMuamba, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnMuambeirosDisp, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnProdutosDisp, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(167, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProdutosDispActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutosDispActionPerformed
        menu.setVisible(false);
        produtos.setVisible(true);
    }//GEN-LAST:event_btnProdutosDispActionPerformed

    private void btnMuambeirosDispActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMuambeirosDispActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMuambeirosDispActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFazerMuamba;
    private javax.swing.JButton btnMuambeirosDisp;
    private javax.swing.JButton btnProdutosDisp;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel8;
    // End of variables declaration//GEN-END:variables
}
